# Data Integration {#data-integration}

(Integration of biological data; Identifier mapping; Entrez; UniProt; BioMart. ID mapping service and match() function.)

## Overview
### Abstract:

Data integration is a challenging problem. This unit discusses the issues and how the large databases solve this with NCBI's Entrez system and the EBI's UniProt Knoledeg Base and BioMart System. R coding exercises put some technical issues in practice.

### Objectives:

This unit will:

  * introduce issue of database integration and how the NCBI and the EBI address this;
  * demonstrate use of Entrez, UniProt and BioMart;
  * teach ID mapping techniques with R.

### Outcomes:

After working through this unit you:

  * are familar with the NCBI and EBI query and retrieval systems;
  * can use BioMart bot online and in R code;
  * can retrieve ID cross references via scripts and match IDs in large tables with R's match() function.

### Deliverables:
**Time management**: Before you begin, estimate how long it will take you to complete this unit. Then, record in your course journal: the number of hours you estimated, the number of hours you worked on the unit, and the amount of time that passed between start and completion of this unit.

**Journal**: Document your progress in your Course Journal. Some tasks may ask you to include specific items in your journal. Don't overlook these.

**Insights**: If you find something particularly noteworthy about this unit, make a note in your insights! page.

### Prerequisites:

This unit builds on material covered in the following prerequisite units:

[BIN-Databases (Bioinformatics Databases)](#bioinfo-databases)<br>
BIN-EBI (Databases and services at the EBI)<br>
BIN-FUNC-Databases (Molecular Function Databases)<br>
[BIN-Miscellaneous_DB (Miscellaneous Databases for Bioinformatics)](#misc-databases)<br>
[BIN-NCBI (The NCBI Database and Services)](#ncbi-services)<br>
BIN-PDB (The RCSB-PDB Structure Database)<br>

`r task_counter <- task_counter + 1`
## Task `r task_counter`

```{block, type="rmd-task"}
Read the introductory notes on [concepts and approaches to data integration in bioinformatics](boris_docs/BIN-Data_integration.pdf).
```

`r task_counter <- task_counter + 1`
## Task `r task_counter`
 
```{block, type="rmd-task"}
  * Visit the [UniProt ID mapping service](https://www.uniprot.org/mapping/), enter NP_010227 into the identifier field, select options from **RefSeq Protein** to **UniProtKB** and click Go.
  * Confirm that this retrieved the right identifier.
  * Also note that you could have searched with a list of IDs, and downloaded the results, e.g. for further processing in R.
```

`r task_counter <- task_counter + 1`
## Task `r task_counter`
 
```{block, type="rmd-task"}

  * Open RStudio and load the ABC-units R project. If you have loaded it before, choose File → Recent projects → ABC-Units. If you have not loaded it before, follow the instructions in the [RPR-Introduction unit](http://steipe.biochemistry.utoronto.ca/abc/index.php/RPR-Introduction).
  * Choose Tools → Version Control → Pull Branches to fetch the most recent version of the project from its GitHub repository with all changes and bug fixes included.
  * Type init() as requested.
  * Open the file BIN-Data_integration.R and follow the instructions.

 
**Note**: take care that you understand all of the code in the script. Evaluation in this course is cumulative and you may be asked to explain any part of code.
```

 
`r task_counter <- task_counter + 1`
## Task `r task_counter`
 
```{block, type="rmd-task"}
  * The biomartr bioconductor package is a second-generation R interface to BioMart that extends the biomaRt package. It has a good quick start introduction to "Functional Annotation".

  * Navigate to [https://www.bioconductor.org/packages/devel/bioc/vignettes/biomaRt/inst/doc/biomaRt.html](https://www.bioconductor.org/packages/devel/bioc/vignettes/biomaRt/inst/doc/biomaRt.html)
  * Work through the tutorial.
```

## Self-evaluation

## Further reading, links and resources
  * [UniProt - NCBI ID mapping](https://www.uniprot.org/help/ncbi_mappings) - detailed information on how it works.
  * Xie & Ahn (2010) Statistical methods for integrating multiple types of high-throughput data. Methods Mol Biol 620:511-29. (pmid: 20652519)<br>
[ [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/20652519) ][ [DOI](https://link.springer.com/protocol/10.1007%2F978-1-60761-580-4_19) ] 

 

**If in doubt, ask!**<br>
If anything about this learning unit is not clear to you, do not proceed blindly but ask for clarification. Post your question on the course mailing list: others are likely to have similar problems. Or send an email to your instructor.

```{block2, type="rmd-original-history"}
<br>**Author**: Boris Steipe <boris.steipe@utoronto.ca> <br>
**Created**: 2017-08-05<br>
**Modified**: 2017-08-05<br>
Version: 1.0<br>
**Version history**:<br>
1.0 Completed to first live version<br>
0.1 First stub<br>
``` 